[package]
name = "coba-parser"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
coba-lexer = { path = "../coba-lexer" }
coba-ast = { path = "../coba-ast" }
